name: Build ProgB

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14.4"

      - name: Install packages
        run: |
          pip install pyinstaller
          pip install customtkinter SpeechRecognition pyjokes edge-tts

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed gui.py

      - uses: actions/upload-artifact@v4
        with:
          name: ProgB-Windows
          path: dist/*

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14.4"

      - name: Install packages
        run: |
          pip install pyinstaller
          pip install customtkinter SpeechRecognition pyjokes edge-tts

      - name: Build Linux Binary
        run: |
          pyinstaller --onefile gui.py

      - uses: actions/upload-artifact@v4
        with:
          name: ProgB-Linux
          path: dist/*